#!/usr/bin/env python3
"""
Hermes Social Tracking Plugin - Alert System
This script checks plugin health and sends alerts.
"""

import sys
import sqlite3
import requests
import smtplib
from pathlib import Path
from datetime import datetime, timedelta
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart

def check_health():
    """Check plugin health and return status."""
    db_path = Path.home() / ".hermes" / "data" / "social_tracking.db"
    health_status = {
        "timestamp": datetime.now().isoformat(),
        "status": "healthy",
        "issues": []
    }
    
    if not db_path.exists():
        health_status["status"] = "critical"
        health_status["issues"].append("Database not found")
        return health_status
    
    try:
        conn = sqlite3.connect(db_path)
        cursor = conn.cursor()
        
        # Check database size
        db_size_mb = db_path.stat().st_size / (1024 * 1024)
        if db_size_mb > 100:
            health_status["issues"].append(f"Database size is large: {db_size_mb:.1f} MB")
        
        # Check last event
        cursor.execute("SELECT timestamp FROM events ORDER BY timestamp DESC LIMIT 1")
        last_event = cursor.fetchone()
        if last_event:
            last_event_time = datetime.fromisoformat(last_event[0].replace('Z', '+00:00'))
            time_since_last_event = datetime.now() - last_event_time
            if time_since_last_event > timedelta(days=7):
                health_status["issues"].append(f"No events in last 7 days (last event: {last_event_time})")
        
        # Check person count
        cursor.execute("SELECT COUNT(*) FROM persons")
        person_count = cursor.fetchone()[0]
        if person_count == 0:
            health_status["issues"].append("No persons tracked in database")
        
        # Check trust scores
        cursor.execute("SELECT AVG(trust_score) FROM persons")
        avg_trust = cursor.fetchone()[0] or 0.0
        if avg_trust < 0.3:
            health_status["issues"].append(f"Average trust score is low: {avg_trust:.3f}")
        
        conn.close()
        
        if not health_status["issues"]:
            health_status["status"] = "healthy"
        
        return health_status
    except Exception as e:
        health_status["status"] = "critical"
        health_status["issues"].append(f"Database error: {str(e)}")
        return health_status

def send_email_alert(health_status, to_email, smtp_server="localhost", smtp_port=587):
    """Send email alert."""
    from_email = "social-tracking-alerts@hermes-agent.com"
    
    msg = MIMEMultipart()
    msg['From'] = from_email
    msg['To'] = to_email
    msg['Subject'] = f"Social Tracking Plugin Alert: {health_status['status'].upper()}"
    
    body = f"""
    Social Tracking Plugin Alert

    Status: {health_status['status']}

    Timestamp: {health_status['timestamp']}

    Issues Found:
    """
    for issue in health_status['issues']:
        body += f"- {issue}\n"
    
    body += f"""

    Please check the plugin and take appropriate action.
    
    This alert was generated by Hermes Social Tracking Plugin.
    """
    
    msg.attach(MIMEText(body, 'plain'))
    
    try:
        with smtplib.SMTP(smtp_server, smtp_port) as server:
            server.starttls()
            server.send_message(msg)
        print(f"✓ Email alert sent to {to_email}")
        return True
    except Exception as e:
        print(f"✗ Failed to send email alert: {e}")
        return False

def send_webhook_alert(health_status, webhook_url):
    """Send webhook alert."""
    try:
        response = requests.post(
            webhook_url,
            json=health_status,
            timeout=10
        )
        if response.status_code == 200:
            print(f"✓ Webhook alert sent to {webhook_url}")
            return True
        else:
            print(f"✗ Failed to send webhook alert: {response.status_code}")
            return False
    except Exception as e:
        print(f"✗ Failed to send webhook alert: {e}")
        return False

def main():
    print("Hermes Social Tracking Plugin - Alert System")
    print("=" * 60)
    
    if len(sys.argv) < 2:
        print("Usage: scripts/alert_system.sh <check|send_email|send_webhook> [options]")
        print("\nExamples:")
        print("  scripts/alert_system.sh check")
        print("  scripts/alert_system.sh send_email recipient@example.com")
        print("  scripts/alert_system.sh send_webhook https://webhook.example.com/social")
        return 1
    
    action = sys.argv[1]
    
    if action == "check":
        health_status = check_health()
        print(f"Health Status: {health_status['status']}")
        if health_status['issues']:
            print("Issues Found:")
            for issue in health_status['issues']:
                print(f"  - {issue}")
        else:
            print("No issues detected")
        return 0 if health_status['status'] == "healthy" else 1
    
    elif action == "send_email":
        if len(sys.argv) < 3:
            print("Please provide recipient email address")
            return 1
        health_status = check_health()
        send_email_alert(health_status, sys.argv[2])
    
    elif action == "send_webhook":
        if len(sys.argv) < 3:
            print("Please provide webhook URL")
            return 1
        health_status = check_health()
        send_webhook_alert(health_status, sys.argv[2])
    
    else:
        print(f"Unknown action: {action}")
        return 1

if __name__ == "__main__":
    sys.exit(main())